// FGengine - a free and open-source library for game development
// Copyright (C) 2025, 2026 Gmunamax <https://github.com/Gmunamax/FGengine>

// This library is free software; you can redistribute it and/or
// modify it under the terms of the GNU Lesser General Public
// License as published by the Free Software Foundation; either
// version 2.1 of the License, or (at your option) any later version.

// This library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// Lesser General Public License for more details.

// You should have received a copy of the GNU Lesser General Public
// License along with this library; if not, see <https://www.gnu.org/licenses/>.
#include <glad/gl.h>

namespace FGengine{

	extern GladGLContext currentPfns;

	void SetCurrentPfns(const GladGLContext&);

}

#define glActiveTexture ::FGengine::currentPfns.ActiveTexture
#define glAttachShader ::FGengine::currentPfns.AttachShader
#define glBeginConditionalRender ::FGengine::currentPfns.BeginConditionalRender
#define glBeginQuery ::FGengine::currentPfns.BeginQuery
#define glBeginQueryIndexed ::FGengine::currentPfns.BeginQueryIndexed
#define glBeginTransformFeedback ::FGengine::currentPfns.BeginTransformFeedback
#define glBindAttribLocation ::FGengine::currentPfns.BindAttribLocation
#define glBindBuffer ::FGengine::currentPfns.BindBuffer
#define glBindBufferBase ::FGengine::currentPfns.BindBufferBase
#define glBindBufferRange ::FGengine::currentPfns.BindBufferRange
#define glBindBuffersBase ::FGengine::currentPfns.BindBuffersBase
#define glBindBuffersRange ::FGengine::currentPfns.BindBuffersRange
#define glBindFragDataLocation ::FGengine::currentPfns.BindFragDataLocation
#define glBindFragDataLocationIndexed ::FGengine::currentPfns.BindFragDataLocationIndexed
#define glBindFramebuffer ::FGengine::currentPfns.BindFramebuffer
#define glBindImageTexture ::FGengine::currentPfns.BindImageTexture
#define glBindImageTextures ::FGengine::currentPfns.BindImageTextures
#define glBindProgramPipeline ::FGengine::currentPfns.BindProgramPipeline
#define glBindRenderbuffer ::FGengine::currentPfns.BindRenderbuffer
#define glBindSampler ::FGengine::currentPfns.BindSampler
#define glBindSamplers ::FGengine::currentPfns.BindSamplers
#define glBindTexture ::FGengine::currentPfns.BindTexture
#define glBindTextureUnit ::FGengine::currentPfns.BindTextureUnit
#define glBindTextures ::FGengine::currentPfns.BindTextures
#define glBindTransformFeedback ::FGengine::currentPfns.BindTransformFeedback
#define glBindVertexArray ::FGengine::currentPfns.BindVertexArray
#define glBindVertexBuffer ::FGengine::currentPfns.BindVertexBuffer
#define glBindVertexBuffers ::FGengine::currentPfns.BindVertexBuffers
#define glBlendColor ::FGengine::currentPfns.BlendColor
#define glBlendEquation ::FGengine::currentPfns.BlendEquation
#define glBlendEquationSeparate ::FGengine::currentPfns.BlendEquationSeparate
#define glBlendEquationSeparatei ::FGengine::currentPfns.BlendEquationSeparatei
#define glBlendEquationi ::FGengine::currentPfns.BlendEquationi
#define glBlendFunc ::FGengine::currentPfns.BlendFunc
#define glBlendFuncSeparate ::FGengine::currentPfns.BlendFuncSeparate
#define glBlendFuncSeparatei ::FGengine::currentPfns.BlendFuncSeparatei
#define glBlendFunci ::FGengine::currentPfns.BlendFunci
#define glBlitFramebuffer ::FGengine::currentPfns.BlitFramebuffer
#define glBlitNamedFramebuffer ::FGengine::currentPfns.BlitNamedFramebuffer
#define glBufferData ::FGengine::currentPfns.BufferData
#define glBufferStorage ::FGengine::currentPfns.BufferStorage
#define glBufferSubData ::FGengine::currentPfns.BufferSubData
#define glCheckFramebufferStatus ::FGengine::currentPfns.CheckFramebufferStatus
#define glCheckNamedFramebufferStatus ::FGengine::currentPfns.CheckNamedFramebufferStatus
#define glClampColor ::FGengine::currentPfns.ClampColor
#define glClear ::FGengine::currentPfns.Clear
#define glClearBufferData ::FGengine::currentPfns.ClearBufferData
#define glClearBufferSubData ::FGengine::currentPfns.ClearBufferSubData
#define glClearBufferfi ::FGengine::currentPfns.ClearBufferfi
#define glClearBufferfv ::FGengine::currentPfns.ClearBufferfv
#define glClearBufferiv ::FGengine::currentPfns.ClearBufferiv
#define glClearBufferuiv ::FGengine::currentPfns.ClearBufferuiv
#define glClearColor ::FGengine::currentPfns.ClearColor
#define glClearDepth ::FGengine::currentPfns.ClearDepth
#define glClearDepthf ::FGengine::currentPfns.ClearDepthf
#define glClearNamedBufferData ::FGengine::currentPfns.ClearNamedBufferData
#define glClearNamedBufferSubData ::FGengine::currentPfns.ClearNamedBufferSubData
#define glClearNamedFramebufferfi ::FGengine::currentPfns.ClearNamedFramebufferfi
#define glClearNamedFramebufferfv ::FGengine::currentPfns.ClearNamedFramebufferfv
#define glClearNamedFramebufferiv ::FGengine::currentPfns.ClearNamedFramebufferiv
#define glClearNamedFramebufferuiv ::FGengine::currentPfns.ClearNamedFramebufferuiv
#define glClearStencil ::FGengine::currentPfns.ClearStencil
#define glClearTexImage ::FGengine::currentPfns.ClearTexImage
#define glClearTexSubImage ::FGengine::currentPfns.ClearTexSubImage
#define glClientWaitSync ::FGengine::currentPfns.ClientWaitSync
#define glClipControl ::FGengine::currentPfns.ClipControl
#define glColorMask ::FGengine::currentPfns.ColorMask
#define glColorMaski ::FGengine::currentPfns.ColorMaski
#define glCompileShader ::FGengine::currentPfns.CompileShader
#define glCompressedTexImage1D ::FGengine::currentPfns.CompressedTexImage1D
#define glCompressedTexImage2D ::FGengine::currentPfns.CompressedTexImage2D
#define glCompressedTexImage3D ::FGengine::currentPfns.CompressedTexImage3D
#define glCompressedTexSubImage1D ::FGengine::currentPfns.CompressedTexSubImage1D
#define glCompressedTexSubImage2D ::FGengine::currentPfns.CompressedTexSubImage2D
#define glCompressedTexSubImage3D ::FGengine::currentPfns.CompressedTexSubImage3D
#define glCompressedTextureSubImage1D ::FGengine::currentPfns.CompressedTextureSubImage1D
#define glCompressedTextureSubImage2D ::FGengine::currentPfns.CompressedTextureSubImage2D
#define glCompressedTextureSubImage3D ::FGengine::currentPfns.CompressedTextureSubImage3D
#define glCopyBufferSubData ::FGengine::currentPfns.CopyBufferSubData
#define glCopyImageSubData ::FGengine::currentPfns.CopyImageSubData
#define glCopyNamedBufferSubData ::FGengine::currentPfns.CopyNamedBufferSubData
#define glCopyTexImage1D ::FGengine::currentPfns.CopyTexImage1D
#define glCopyTexImage2D ::FGengine::currentPfns.CopyTexImage2D
#define glCopyTexSubImage1D ::FGengine::currentPfns.CopyTexSubImage1D
#define glCopyTexSubImage2D ::FGengine::currentPfns.CopyTexSubImage2D
#define glCopyTexSubImage3D ::FGengine::currentPfns.CopyTexSubImage3D
#define glCopyTextureSubImage1D ::FGengine::currentPfns.CopyTextureSubImage1D
#define glCopyTextureSubImage2D ::FGengine::currentPfns.CopyTextureSubImage2D
#define glCopyTextureSubImage3D ::FGengine::currentPfns.CopyTextureSubImage3D
#define glCreateBuffers ::FGengine::currentPfns.CreateBuffers
#define glCreateFramebuffers ::FGengine::currentPfns.CreateFramebuffers
#define glCreateProgram ::FGengine::currentPfns.CreateProgram
#define glCreateProgramPipelines ::FGengine::currentPfns.CreateProgramPipelines
#define glCreateQueries ::FGengine::currentPfns.CreateQueries
#define glCreateRenderbuffers ::FGengine::currentPfns.CreateRenderbuffers
#define glCreateSamplers ::FGengine::currentPfns.CreateSamplers
#define glCreateShader ::FGengine::currentPfns.CreateShader
#define glCreateShaderProgramv ::FGengine::currentPfns.CreateShaderProgramv
#define glCreateTextures ::FGengine::currentPfns.CreateTextures
#define glCreateTransformFeedbacks ::FGengine::currentPfns.CreateTransformFeedbacks
#define glCreateVertexArrays ::FGengine::currentPfns.CreateVertexArrays
#define glCullFace ::FGengine::currentPfns.CullFace
#define glDebugMessageCallback ::FGengine::currentPfns.DebugMessageCallback
#define glDebugMessageControl ::FGengine::currentPfns.DebugMessageControl
#define glDebugMessageInsert ::FGengine::currentPfns.DebugMessageInsert
#define glDeleteBuffers ::FGengine::currentPfns.DeleteBuffers
#define glDeleteFramebuffers ::FGengine::currentPfns.DeleteFramebuffers
#define glDeleteProgram ::FGengine::currentPfns.DeleteProgram
#define glDeleteProgramPipelines ::FGengine::currentPfns.DeleteProgramPipelines
#define glDeleteQueries ::FGengine::currentPfns.DeleteQueries
#define glDeleteRenderbuffers ::FGengine::currentPfns.DeleteRenderbuffers
#define glDeleteSamplers ::FGengine::currentPfns.DeleteSamplers
#define glDeleteShader ::FGengine::currentPfns.DeleteShader
#define glDeleteSync ::FGengine::currentPfns.DeleteSync
#define glDeleteTextures ::FGengine::currentPfns.DeleteTextures
#define glDeleteTransformFeedbacks ::FGengine::currentPfns.DeleteTransformFeedbacks
#define glDeleteVertexArrays ::FGengine::currentPfns.DeleteVertexArrays
#define glDepthFunc ::FGengine::currentPfns.DepthFunc
#define glDepthMask ::FGengine::currentPfns.DepthMask
#define glDepthRange ::FGengine::currentPfns.DepthRange
#define glDepthRangeArrayv ::FGengine::currentPfns.DepthRangeArrayv
#define glDepthRangeIndexed ::FGengine::currentPfns.DepthRangeIndexed
#define glDepthRangef ::FGengine::currentPfns.DepthRangef
#define glDetachShader ::FGengine::currentPfns.DetachShader
#define glDisable ::FGengine::currentPfns.Disable
#define glDisableVertexArrayAttrib ::FGengine::currentPfns.DisableVertexArrayAttrib
#define glDisableVertexAttribArray ::FGengine::currentPfns.DisableVertexAttribArray
#define glDisablei ::FGengine::currentPfns.Disablei
#define glDispatchCompute ::FGengine::currentPfns.DispatchCompute
#define glDispatchComputeIndirect ::FGengine::currentPfns.DispatchComputeIndirect
#define glDrawArrays ::FGengine::currentPfns.DrawArrays
#define glDrawArraysIndirect ::FGengine::currentPfns.DrawArraysIndirect
#define glDrawArraysInstanced ::FGengine::currentPfns.DrawArraysInstanced
#define glDrawArraysInstancedBaseInstance ::FGengine::currentPfns.DrawArraysInstancedBaseInstance
#define glDrawBuffer ::FGengine::currentPfns.DrawBuffer
#define glDrawBuffers ::FGengine::currentPfns.DrawBuffers
#define glDrawElements ::FGengine::currentPfns.DrawElements
#define glDrawElementsBaseVertex ::FGengine::currentPfns.DrawElementsBaseVertex
#define glDrawElementsIndirect ::FGengine::currentPfns.DrawElementsIndirect
#define glDrawElementsInstanced ::FGengine::currentPfns.DrawElementsInstanced
#define glDrawElementsInstancedBaseInstance ::FGengine::currentPfns.DrawElementsInstancedBaseInstance
#define glDrawElementsInstancedBaseVertex ::FGengine::currentPfns.DrawElementsInstancedBaseVertex
#define glDrawElementsInstancedBaseVertexBaseInstance ::FGengine::currentPfns.DrawElementsInstancedBaseVertexBaseInstance
#define glDrawRangeElements ::FGengine::currentPfns.DrawRangeElements
#define glDrawRangeElementsBaseVertex ::FGengine::currentPfns.DrawRangeElementsBaseVertex
#define glDrawTransformFeedback ::FGengine::currentPfns.DrawTransformFeedback
#define glDrawTransformFeedbackInstanced ::FGengine::currentPfns.DrawTransformFeedbackInstanced
#define glDrawTransformFeedbackStream ::FGengine::currentPfns.DrawTransformFeedbackStream
#define glDrawTransformFeedbackStreamInstanced ::FGengine::currentPfns.DrawTransformFeedbackStreamInstanced
#define glEnable ::FGengine::currentPfns.Enable
#define glEnableVertexArrayAttrib ::FGengine::currentPfns.EnableVertexArrayAttrib
#define glEnableVertexAttribArray ::FGengine::currentPfns.EnableVertexAttribArray
#define glEnablei ::FGengine::currentPfns.Enablei
#define glEndConditionalRender ::FGengine::currentPfns.EndConditionalRender
#define glEndQuery ::FGengine::currentPfns.EndQuery
#define glEndQueryIndexed ::FGengine::currentPfns.EndQueryIndexed
#define glEndTransformFeedback ::FGengine::currentPfns.EndTransformFeedback
#define glFenceSync ::FGengine::currentPfns.FenceSync
#define glFinish ::FGengine::currentPfns.Finish
#define glFlush ::FGengine::currentPfns.Flush
#define glFlushMappedBufferRange ::FGengine::currentPfns.FlushMappedBufferRange
#define glFlushMappedNamedBufferRange ::FGengine::currentPfns.FlushMappedNamedBufferRange
#define glFramebufferParameteri ::FGengine::currentPfns.FramebufferParameteri
#define glFramebufferRenderbuffer ::FGengine::currentPfns.FramebufferRenderbuffer
#define glFramebufferTexture ::FGengine::currentPfns.FramebufferTexture
#define glFramebufferTexture1D ::FGengine::currentPfns.FramebufferTexture1D
#define glFramebufferTexture2D ::FGengine::currentPfns.FramebufferTexture2D
#define glFramebufferTexture3D ::FGengine::currentPfns.FramebufferTexture3D
#define glFramebufferTextureLayer ::FGengine::currentPfns.FramebufferTextureLayer
#define glFrontFace ::FGengine::currentPfns.FrontFace
#define glGenBuffers ::FGengine::currentPfns.GenBuffers
#define glGenFramebuffers ::FGengine::currentPfns.GenFramebuffers
#define glGenProgramPipelines ::FGengine::currentPfns.GenProgramPipelines
#define glGenQueries ::FGengine::currentPfns.GenQueries
#define glGenRenderbuffers ::FGengine::currentPfns.GenRenderbuffers
#define glGenSamplers ::FGengine::currentPfns.GenSamplers
#define glGenTextures ::FGengine::currentPfns.GenTextures
#define glGenTransformFeedbacks ::FGengine::currentPfns.GenTransformFeedbacks
#define glGenVertexArrays ::FGengine::currentPfns.GenVertexArrays
#define glGenerateMipmap ::FGengine::currentPfns.GenerateMipmap
#define glGenerateTextureMipmap ::FGengine::currentPfns.GenerateTextureMipmap
#define glGetActiveAtomicCounterBufferiv ::FGengine::currentPfns.GetActiveAtomicCounterBufferiv
#define glGetActiveAttrib ::FGengine::currentPfns.GetActiveAttrib
#define glGetActiveSubroutineName ::FGengine::currentPfns.GetActiveSubroutineName
#define glGetActiveSubroutineUniformName ::FGengine::currentPfns.GetActiveSubroutineUniformName
#define glGetActiveSubroutineUniformiv ::FGengine::currentPfns.GetActiveSubroutineUniformiv
#define glGetActiveUniform ::FGengine::currentPfns.GetActiveUniform
#define glGetActiveUniformBlockName ::FGengine::currentPfns.GetActiveUniformBlockName
#define glGetActiveUniformBlockiv ::FGengine::currentPfns.GetActiveUniformBlockiv
#define glGetActiveUniformName ::FGengine::currentPfns.GetActiveUniformName
#define glGetActiveUniformsiv ::FGengine::currentPfns.GetActiveUniformsiv
#define glGetAttachedShaders ::FGengine::currentPfns.GetAttachedShaders
#define glGetAttribLocation ::FGengine::currentPfns.GetAttribLocation
#define glGetBooleani_v ::FGengine::currentPfns.GetBooleani_v
#define glGetBooleanv ::FGengine::currentPfns.GetBooleanv
#define glGetBufferParameteri64v ::FGengine::currentPfns.GetBufferParameteri64v
#define glGetBufferParameteriv ::FGengine::currentPfns.GetBufferParameteriv
#define glGetBufferPointerv ::FGengine::currentPfns.GetBufferPointerv
#define glGetBufferSubData ::FGengine::currentPfns.GetBufferSubData
#define glGetCompressedTexImage ::FGengine::currentPfns.GetCompressedTexImage
#define glGetCompressedTextureImage ::FGengine::currentPfns.GetCompressedTextureImage
#define glGetCompressedTextureSubImage ::FGengine::currentPfns.GetCompressedTextureSubImage
#define glGetDebugMessageLog ::FGengine::currentPfns.GetDebugMessageLog
#define glGetDoublei_v ::FGengine::currentPfns.GetDoublei_v
#define glGetDoublev ::FGengine::currentPfns.GetDoublev
#define glGetError ::FGengine::currentPfns.GetError
#define glGetFloati_v ::FGengine::currentPfns.GetFloati_v
#define glGetFloatv ::FGengine::currentPfns.GetFloatv
#define glGetFragDataIndex ::FGengine::currentPfns.GetFragDataIndex
#define glGetFragDataLocation ::FGengine::currentPfns.GetFragDataLocation
#define glGetFramebufferAttachmentParameteriv ::FGengine::currentPfns.GetFramebufferAttachmentParameteriv
#define glGetFramebufferParameteriv ::FGengine::currentPfns.GetFramebufferParameteriv
#define glGetGraphicsResetStatus ::FGengine::currentPfns.GetGraphicsResetStatus
#define glGetInteger64i_v ::FGengine::currentPfns.GetInteger64i_v
#define glGetInteger64v ::FGengine::currentPfns.GetInteger64v
#define glGetIntegeri_v ::FGengine::currentPfns.GetIntegeri_v
#define glGetIntegerv ::FGengine::currentPfns.GetIntegerv
#define glGetInternalformati64v ::FGengine::currentPfns.GetInternalformati64v
#define glGetInternalformativ ::FGengine::currentPfns.GetInternalformativ
#define glGetMultisamplefv ::FGengine::currentPfns.GetMultisamplefv
#define glGetNamedBufferParameteri64v ::FGengine::currentPfns.GetNamedBufferParameteri64v
#define glGetNamedBufferParameteriv ::FGengine::currentPfns.GetNamedBufferParameteriv
#define glGetNamedBufferPointerv ::FGengine::currentPfns.GetNamedBufferPointerv
#define glGetNamedBufferSubData ::FGengine::currentPfns.GetNamedBufferSubData
#define glGetNamedFramebufferAttachmentParameteriv ::FGengine::currentPfns.GetNamedFramebufferAttachmentParameteriv
#define glGetNamedFramebufferParameteriv ::FGengine::currentPfns.GetNamedFramebufferParameteriv
#define glGetNamedRenderbufferParameteriv ::FGengine::currentPfns.GetNamedRenderbufferParameteriv
#define glGetObjectLabel ::FGengine::currentPfns.GetObjectLabel
#define glGetObjectPtrLabel ::FGengine::currentPfns.GetObjectPtrLabel
#define glGetPointerv ::FGengine::currentPfns.GetPointerv
#define glGetProgramBinary ::FGengine::currentPfns.GetProgramBinary
#define glGetProgramInfoLog ::FGengine::currentPfns.GetProgramInfoLog
#define glGetProgramInterfaceiv ::FGengine::currentPfns.GetProgramInterfaceiv
#define glGetProgramPipelineInfoLog ::FGengine::currentPfns.GetProgramPipelineInfoLog
#define glGetProgramPipelineiv ::FGengine::currentPfns.GetProgramPipelineiv
#define glGetProgramResourceIndex ::FGengine::currentPfns.GetProgramResourceIndex
#define glGetProgramResourceLocation ::FGengine::currentPfns.GetProgramResourceLocation
#define glGetProgramResourceLocationIndex ::FGengine::currentPfns.GetProgramResourceLocationIndex
#define glGetProgramResourceName ::FGengine::currentPfns.GetProgramResourceName
#define glGetProgramResourceiv ::FGengine::currentPfns.GetProgramResourceiv
#define glGetProgramStageiv ::FGengine::currentPfns.GetProgramStageiv
#define glGetProgramiv ::FGengine::currentPfns.GetProgramiv
#define glGetQueryBufferObjecti64v ::FGengine::currentPfns.GetQueryBufferObjecti64v
#define glGetQueryBufferObjectiv ::FGengine::currentPfns.GetQueryBufferObjectiv
#define glGetQueryBufferObjectui64v ::FGengine::currentPfns.GetQueryBufferObjectui64v
#define glGetQueryBufferObjectuiv ::FGengine::currentPfns.GetQueryBufferObjectuiv
#define glGetQueryIndexediv ::FGengine::currentPfns.GetQueryIndexediv
#define glGetQueryObjecti64v ::FGengine::currentPfns.GetQueryObjecti64v
#define glGetQueryObjectiv ::FGengine::currentPfns.GetQueryObjectiv
#define glGetQueryObjectui64v ::FGengine::currentPfns.GetQueryObjectui64v
#define glGetQueryObjectuiv ::FGengine::currentPfns.GetQueryObjectuiv
#define glGetQueryiv ::FGengine::currentPfns.GetQueryiv
#define glGetRenderbufferParameteriv ::FGengine::currentPfns.GetRenderbufferParameteriv
#define glGetSamplerParameterIiv ::FGengine::currentPfns.GetSamplerParameterIiv
#define glGetSamplerParameterIuiv ::FGengine::currentPfns.GetSamplerParameterIuiv
#define glGetSamplerParameterfv ::FGengine::currentPfns.GetSamplerParameterfv
#define glGetSamplerParameteriv ::FGengine::currentPfns.GetSamplerParameteriv
#define glGetShaderInfoLog ::FGengine::currentPfns.GetShaderInfoLog
#define glGetShaderPrecisionFormat ::FGengine::currentPfns.GetShaderPrecisionFormat
#define glGetShaderSource ::FGengine::currentPfns.GetShaderSource
#define glGetShaderiv ::FGengine::currentPfns.GetShaderiv
#define glGetString ::FGengine::currentPfns.GetString
#define glGetStringi ::FGengine::currentPfns.GetStringi
#define glGetSubroutineIndex ::FGengine::currentPfns.GetSubroutineIndex
#define glGetSubroutineUniformLocation ::FGengine::currentPfns.GetSubroutineUniformLocation
#define glGetSynciv ::FGengine::currentPfns.GetSynciv
#define glGetTexImage ::FGengine::currentPfns.GetTexImage
#define glGetTexLevelParameterfv ::FGengine::currentPfns.GetTexLevelParameterfv
#define glGetTexLevelParameteriv ::FGengine::currentPfns.GetTexLevelParameteriv
#define glGetTexParameterIiv ::FGengine::currentPfns.GetTexParameterIiv
#define glGetTexParameterIuiv ::FGengine::currentPfns.GetTexParameterIuiv
#define glGetTexParameterfv ::FGengine::currentPfns.GetTexParameterfv
#define glGetTexParameteriv ::FGengine::currentPfns.GetTexParameteriv
#define glGetTextureImage ::FGengine::currentPfns.GetTextureImage
#define glGetTextureLevelParameterfv ::FGengine::currentPfns.GetTextureLevelParameterfv
#define glGetTextureLevelParameteriv ::FGengine::currentPfns.GetTextureLevelParameteriv
#define glGetTextureParameterIiv ::FGengine::currentPfns.GetTextureParameterIiv
#define glGetTextureParameterIuiv ::FGengine::currentPfns.GetTextureParameterIuiv
#define glGetTextureParameterfv ::FGengine::currentPfns.GetTextureParameterfv
#define glGetTextureParameteriv ::FGengine::currentPfns.GetTextureParameteriv
#define glGetTextureSubImage ::FGengine::currentPfns.GetTextureSubImage
#define glGetTransformFeedbackVarying ::FGengine::currentPfns.GetTransformFeedbackVarying
#define glGetTransformFeedbacki64_v ::FGengine::currentPfns.GetTransformFeedbacki64_v
#define glGetTransformFeedbacki_v ::FGengine::currentPfns.GetTransformFeedbacki_v
#define glGetTransformFeedbackiv ::FGengine::currentPfns.GetTransformFeedbackiv
#define glGetUniformBlockIndex ::FGengine::currentPfns.GetUniformBlockIndex
#define glGetUniformIndices ::FGengine::currentPfns.GetUniformIndices
#define glGetUniformLocation ::FGengine::currentPfns.GetUniformLocation
#define glGetUniformSubroutineuiv ::FGengine::currentPfns.GetUniformSubroutineuiv
#define glGetUniformdv ::FGengine::currentPfns.GetUniformdv
#define glGetUniformfv ::FGengine::currentPfns.GetUniformfv
#define glGetUniformiv ::FGengine::currentPfns.GetUniformiv
#define glGetUniformuiv ::FGengine::currentPfns.GetUniformuiv
#define glGetVertexArrayIndexed64iv ::FGengine::currentPfns.GetVertexArrayIndexed64iv
#define glGetVertexArrayIndexediv ::FGengine::currentPfns.GetVertexArrayIndexediv
#define glGetVertexArrayiv ::FGengine::currentPfns.GetVertexArrayiv
#define glGetVertexAttribIiv ::FGengine::currentPfns.GetVertexAttribIiv
#define glGetVertexAttribIuiv ::FGengine::currentPfns.GetVertexAttribIuiv
#define glGetVertexAttribLdv ::FGengine::currentPfns.GetVertexAttribLdv
#define glGetVertexAttribPointerv ::FGengine::currentPfns.GetVertexAttribPointerv
#define glGetVertexAttribdv ::FGengine::currentPfns.GetVertexAttribdv
#define glGetVertexAttribfv ::FGengine::currentPfns.GetVertexAttribfv
#define glGetVertexAttribiv ::FGengine::currentPfns.GetVertexAttribiv
#define glGetnCompressedTexImage ::FGengine::currentPfns.GetnCompressedTexImage
#define glGetnTexImage ::FGengine::currentPfns.GetnTexImage
#define glGetnUniformdv ::FGengine::currentPfns.GetnUniformdv
#define glGetnUniformfv ::FGengine::currentPfns.GetnUniformfv
#define glGetnUniformiv ::FGengine::currentPfns.GetnUniformiv
#define glGetnUniformuiv ::FGengine::currentPfns.GetnUniformuiv
#define glHint ::FGengine::currentPfns.Hint
#define glInvalidateBufferData ::FGengine::currentPfns.InvalidateBufferData
#define glInvalidateBufferSubData ::FGengine::currentPfns.InvalidateBufferSubData
#define glInvalidateFramebuffer ::FGengine::currentPfns.InvalidateFramebuffer
#define glInvalidateNamedFramebufferData ::FGengine::currentPfns.InvalidateNamedFramebufferData
#define glInvalidateNamedFramebufferSubData ::FGengine::currentPfns.InvalidateNamedFramebufferSubData
#define glInvalidateSubFramebuffer ::FGengine::currentPfns.InvalidateSubFramebuffer
#define glInvalidateTexImage ::FGengine::currentPfns.InvalidateTexImage
#define glInvalidateTexSubImage ::FGengine::currentPfns.InvalidateTexSubImage
#define glIsBuffer ::FGengine::currentPfns.IsBuffer
#define glIsEnabled ::FGengine::currentPfns.IsEnabled
#define glIsEnabledi ::FGengine::currentPfns.IsEnabledi
#define glIsFramebuffer ::FGengine::currentPfns.IsFramebuffer
#define glIsProgram ::FGengine::currentPfns.IsProgram
#define glIsProgramPipeline ::FGengine::currentPfns.IsProgramPipeline
#define glIsQuery ::FGengine::currentPfns.IsQuery
#define glIsRenderbuffer ::FGengine::currentPfns.IsRenderbuffer
#define glIsSampler ::FGengine::currentPfns.IsSampler
#define glIsShader ::FGengine::currentPfns.IsShader
#define glIsSync ::FGengine::currentPfns.IsSync
#define glIsTexture ::FGengine::currentPfns.IsTexture
#define glIsTransformFeedback ::FGengine::currentPfns.IsTransformFeedback
#define glIsVertexArray ::FGengine::currentPfns.IsVertexArray
#define glLineWidth ::FGengine::currentPfns.LineWidth
#define glLinkProgram ::FGengine::currentPfns.LinkProgram
#define glLogicOp ::FGengine::currentPfns.LogicOp
#define glMapBuffer ::FGengine::currentPfns.MapBuffer
#define glMapBufferRange ::FGengine::currentPfns.MapBufferRange
#define glMapNamedBuffer ::FGengine::currentPfns.MapNamedBuffer
#define glMapNamedBufferRange ::FGengine::currentPfns.MapNamedBufferRange
#define glMemoryBarrier ::FGengine::currentPfns.MemoryBarrier
#define glMemoryBarrierByRegion ::FGengine::currentPfns.MemoryBarrierByRegion
#define glMinSampleShading ::FGengine::currentPfns.MinSampleShading
#define glMultiDrawArrays ::FGengine::currentPfns.MultiDrawArrays
#define glMultiDrawArraysIndirect ::FGengine::currentPfns.MultiDrawArraysIndirect
#define glMultiDrawArraysIndirectCount ::FGengine::currentPfns.MultiDrawArraysIndirectCount
#define glMultiDrawElements ::FGengine::currentPfns.MultiDrawElements
#define glMultiDrawElementsBaseVertex ::FGengine::currentPfns.MultiDrawElementsBaseVertex
#define glMultiDrawElementsIndirect ::FGengine::currentPfns.MultiDrawElementsIndirect
#define glMultiDrawElementsIndirectCount ::FGengine::currentPfns.MultiDrawElementsIndirectCount
#define glNamedBufferData ::FGengine::currentPfns.NamedBufferData
#define glNamedBufferStorage ::FGengine::currentPfns.NamedBufferStorage
#define glNamedBufferSubData ::FGengine::currentPfns.NamedBufferSubData
#define glNamedFramebufferDrawBuffer ::FGengine::currentPfns.NamedFramebufferDrawBuffer
#define glNamedFramebufferDrawBuffers ::FGengine::currentPfns.NamedFramebufferDrawBuffers
#define glNamedFramebufferParameteri ::FGengine::currentPfns.NamedFramebufferParameteri
#define glNamedFramebufferReadBuffer ::FGengine::currentPfns.NamedFramebufferReadBuffer
#define glNamedFramebufferRenderbuffer ::FGengine::currentPfns.NamedFramebufferRenderbuffer
#define glNamedFramebufferTexture ::FGengine::currentPfns.NamedFramebufferTexture
#define glNamedFramebufferTextureLayer ::FGengine::currentPfns.NamedFramebufferTextureLayer
#define glNamedRenderbufferStorage ::FGengine::currentPfns.NamedRenderbufferStorage
#define glNamedRenderbufferStorageMultisample ::FGengine::currentPfns.NamedRenderbufferStorageMultisample
#define glObjectLabel ::FGengine::currentPfns.ObjectLabel
#define glObjectPtrLabel ::FGengine::currentPfns.ObjectPtrLabel
#define glPatchParameterfv ::FGengine::currentPfns.PatchParameterfv
#define glPatchParameteri ::FGengine::currentPfns.PatchParameteri
#define glPauseTransformFeedback ::FGengine::currentPfns.PauseTransformFeedback
#define glPixelStoref ::FGengine::currentPfns.PixelStoref
#define glPixelStorei ::FGengine::currentPfns.PixelStorei
#define glPointParameterf ::FGengine::currentPfns.PointParameterf
#define glPointParameterfv ::FGengine::currentPfns.PointParameterfv
#define glPointParameteri ::FGengine::currentPfns.PointParameteri
#define glPointParameteriv ::FGengine::currentPfns.PointParameteriv
#define glPointSize ::FGengine::currentPfns.PointSize
#define glPolygonMode ::FGengine::currentPfns.PolygonMode
#define glPolygonOffset ::FGengine::currentPfns.PolygonOffset
#define glPolygonOffsetClamp ::FGengine::currentPfns.PolygonOffsetClamp
#define glPopDebugGroup ::FGengine::currentPfns.PopDebugGroup
#define glPrimitiveRestartIndex ::FGengine::currentPfns.PrimitiveRestartIndex
#define glProgramBinary ::FGengine::currentPfns.ProgramBinary
#define glProgramParameteri ::FGengine::currentPfns.ProgramParameteri
#define glProgramUniform1d ::FGengine::currentPfns.ProgramUniform1d
#define glProgramUniform1dv ::FGengine::currentPfns.ProgramUniform1dv
#define glProgramUniform1f ::FGengine::currentPfns.ProgramUniform1f
#define glProgramUniform1fv ::FGengine::currentPfns.ProgramUniform1fv
#define glProgramUniform1i ::FGengine::currentPfns.ProgramUniform1i
#define glProgramUniform1iv ::FGengine::currentPfns.ProgramUniform1iv
#define glProgramUniform1ui ::FGengine::currentPfns.ProgramUniform1ui
#define glProgramUniform1uiv ::FGengine::currentPfns.ProgramUniform1uiv
#define glProgramUniform2d ::FGengine::currentPfns.ProgramUniform2d
#define glProgramUniform2dv ::FGengine::currentPfns.ProgramUniform2dv
#define glProgramUniform2f ::FGengine::currentPfns.ProgramUniform2f
#define glProgramUniform2fv ::FGengine::currentPfns.ProgramUniform2fv
#define glProgramUniform2i ::FGengine::currentPfns.ProgramUniform2i
#define glProgramUniform2iv ::FGengine::currentPfns.ProgramUniform2iv
#define glProgramUniform2ui ::FGengine::currentPfns.ProgramUniform2ui
#define glProgramUniform2uiv ::FGengine::currentPfns.ProgramUniform2uiv
#define glProgramUniform3d ::FGengine::currentPfns.ProgramUniform3d
#define glProgramUniform3dv ::FGengine::currentPfns.ProgramUniform3dv
#define glProgramUniform3f ::FGengine::currentPfns.ProgramUniform3f
#define glProgramUniform3fv ::FGengine::currentPfns.ProgramUniform3fv
#define glProgramUniform3i ::FGengine::currentPfns.ProgramUniform3i
#define glProgramUniform3iv ::FGengine::currentPfns.ProgramUniform3iv
#define glProgramUniform3ui ::FGengine::currentPfns.ProgramUniform3ui
#define glProgramUniform3uiv ::FGengine::currentPfns.ProgramUniform3uiv
#define glProgramUniform4d ::FGengine::currentPfns.ProgramUniform4d
#define glProgramUniform4dv ::FGengine::currentPfns.ProgramUniform4dv
#define glProgramUniform4f ::FGengine::currentPfns.ProgramUniform4f
#define glProgramUniform4fv ::FGengine::currentPfns.ProgramUniform4fv
#define glProgramUniform4i ::FGengine::currentPfns.ProgramUniform4i
#define glProgramUniform4iv ::FGengine::currentPfns.ProgramUniform4iv
#define glProgramUniform4ui ::FGengine::currentPfns.ProgramUniform4ui
#define glProgramUniform4uiv ::FGengine::currentPfns.ProgramUniform4uiv
#define glProgramUniformMatrix2dv ::FGengine::currentPfns.ProgramUniformMatrix2dv
#define glProgramUniformMatrix2fv ::FGengine::currentPfns.ProgramUniformMatrix2fv
#define glProgramUniformMatrix2x3dv ::FGengine::currentPfns.ProgramUniformMatrix2x3dv
#define glProgramUniformMatrix2x3fv ::FGengine::currentPfns.ProgramUniformMatrix2x3fv
#define glProgramUniformMatrix2x4dv ::FGengine::currentPfns.ProgramUniformMatrix2x4dv
#define glProgramUniformMatrix2x4fv ::FGengine::currentPfns.ProgramUniformMatrix2x4fv
#define glProgramUniformMatrix3dv ::FGengine::currentPfns.ProgramUniformMatrix3dv
#define glProgramUniformMatrix3fv ::FGengine::currentPfns.ProgramUniformMatrix3fv
#define glProgramUniformMatrix3x2dv ::FGengine::currentPfns.ProgramUniformMatrix3x2dv
#define glProgramUniformMatrix3x2fv ::FGengine::currentPfns.ProgramUniformMatrix3x2fv
#define glProgramUniformMatrix3x4dv ::FGengine::currentPfns.ProgramUniformMatrix3x4dv
#define glProgramUniformMatrix3x4fv ::FGengine::currentPfns.ProgramUniformMatrix3x4fv
#define glProgramUniformMatrix4dv ::FGengine::currentPfns.ProgramUniformMatrix4dv
#define glProgramUniformMatrix4fv ::FGengine::currentPfns.ProgramUniformMatrix4fv
#define glProgramUniformMatrix4x2dv ::FGengine::currentPfns.ProgramUniformMatrix4x2dv
#define glProgramUniformMatrix4x2fv ::FGengine::currentPfns.ProgramUniformMatrix4x2fv
#define glProgramUniformMatrix4x3dv ::FGengine::currentPfns.ProgramUniformMatrix4x3dv
#define glProgramUniformMatrix4x3fv ::FGengine::currentPfns.ProgramUniformMatrix4x3fv
#define glProvokingVertex ::FGengine::currentPfns.ProvokingVertex
#define glPushDebugGroup ::FGengine::currentPfns.PushDebugGroup
#define glQueryCounter ::FGengine::currentPfns.QueryCounter
#define glReadBuffer ::FGengine::currentPfns.ReadBuffer
#define glReadPixels ::FGengine::currentPfns.ReadPixels
#define glReadnPixels ::FGengine::currentPfns.ReadnPixels
#define glReleaseShaderCompiler ::FGengine::currentPfns.ReleaseShaderCompiler
#define glRenderbufferStorage ::FGengine::currentPfns.RenderbufferStorage
#define glRenderbufferStorageMultisample ::FGengine::currentPfns.RenderbufferStorageMultisample
#define glResumeTransformFeedback ::FGengine::currentPfns.ResumeTransformFeedback
#define glSampleCoverage ::FGengine::currentPfns.SampleCoverage
#define glSampleMaski ::FGengine::currentPfns.SampleMaski
#define glSamplerParameterIiv ::FGengine::currentPfns.SamplerParameterIiv
#define glSamplerParameterIuiv ::FGengine::currentPfns.SamplerParameterIuiv
#define glSamplerParameterf ::FGengine::currentPfns.SamplerParameterf
#define glSamplerParameterfv ::FGengine::currentPfns.SamplerParameterfv
#define glSamplerParameteri ::FGengine::currentPfns.SamplerParameteri
#define glSamplerParameteriv ::FGengine::currentPfns.SamplerParameteriv
#define glScissor ::FGengine::currentPfns.Scissor
#define glScissorArrayv ::FGengine::currentPfns.ScissorArrayv
#define glScissorIndexed ::FGengine::currentPfns.ScissorIndexed
#define glScissorIndexedv ::FGengine::currentPfns.ScissorIndexedv
#define glShaderBinary ::FGengine::currentPfns.ShaderBinary
#define glShaderSource ::FGengine::currentPfns.ShaderSource
#define glShaderStorageBlockBinding ::FGengine::currentPfns.ShaderStorageBlockBinding
#define glSpecializeShader ::FGengine::currentPfns.SpecializeShader
#define glStencilFunc ::FGengine::currentPfns.StencilFunc
#define glStencilFuncSeparate ::FGengine::currentPfns.StencilFuncSeparate
#define glStencilMask ::FGengine::currentPfns.StencilMask
#define glStencilMaskSeparate ::FGengine::currentPfns.StencilMaskSeparate
#define glStencilOp ::FGengine::currentPfns.StencilOp
#define glStencilOpSeparate ::FGengine::currentPfns.StencilOpSeparate
#define glTexBuffer ::FGengine::currentPfns.TexBuffer
#define glTexBufferRange ::FGengine::currentPfns.TexBufferRange
#define glTexImage1D ::FGengine::currentPfns.TexImage1D
#define glTexImage2D ::FGengine::currentPfns.TexImage2D
#define glTexImage2DMultisample ::FGengine::currentPfns.TexImage2DMultisample
#define glTexImage3D ::FGengine::currentPfns.TexImage3D
#define glTexImage3DMultisample ::FGengine::currentPfns.TexImage3DMultisample
#define glTexParameterIiv ::FGengine::currentPfns.TexParameterIiv
#define glTexParameterIuiv ::FGengine::currentPfns.TexParameterIuiv
#define glTexParameterf ::FGengine::currentPfns.TexParameterf
#define glTexParameterfv ::FGengine::currentPfns.TexParameterfv
#define glTexParameteri ::FGengine::currentPfns.TexParameteri
#define glTexParameteriv ::FGengine::currentPfns.TexParameteriv
#define glTexStorage1D ::FGengine::currentPfns.TexStorage1D
#define glTexStorage2D ::FGengine::currentPfns.TexStorage2D
#define glTexStorage2DMultisample ::FGengine::currentPfns.TexStorage2DMultisample
#define glTexStorage3D ::FGengine::currentPfns.TexStorage3D
#define glTexStorage3DMultisample ::FGengine::currentPfns.TexStorage3DMultisample
#define glTexSubImage1D ::FGengine::currentPfns.TexSubImage1D
#define glTexSubImage2D ::FGengine::currentPfns.TexSubImage2D
#define glTexSubImage3D ::FGengine::currentPfns.TexSubImage3D
#define glTextureBarrier ::FGengine::currentPfns.TextureBarrier
#define glTextureBuffer ::FGengine::currentPfns.TextureBuffer
#define glTextureBufferRange ::FGengine::currentPfns.TextureBufferRange
#define glTextureParameterIiv ::FGengine::currentPfns.TextureParameterIiv
#define glTextureParameterIuiv ::FGengine::currentPfns.TextureParameterIuiv
#define glTextureParameterf ::FGengine::currentPfns.TextureParameterf
#define glTextureParameterfv ::FGengine::currentPfns.TextureParameterfv
#define glTextureParameteri ::FGengine::currentPfns.TextureParameteri
#define glTextureParameteriv ::FGengine::currentPfns.TextureParameteriv
#define glTextureStorage1D ::FGengine::currentPfns.TextureStorage1D
#define glTextureStorage2D ::FGengine::currentPfns.TextureStorage2D
#define glTextureStorage2DMultisample ::FGengine::currentPfns.TextureStorage2DMultisample
#define glTextureStorage3D ::FGengine::currentPfns.TextureStorage3D
#define glTextureStorage3DMultisample ::FGengine::currentPfns.TextureStorage3DMultisample
#define glTextureSubImage1D ::FGengine::currentPfns.TextureSubImage1D
#define glTextureSubImage2D ::FGengine::currentPfns.TextureSubImage2D
#define glTextureSubImage3D ::FGengine::currentPfns.TextureSubImage3D
#define glTextureView ::FGengine::currentPfns.TextureView
#define glTransformFeedbackBufferBase ::FGengine::currentPfns.TransformFeedbackBufferBase
#define glTransformFeedbackBufferRange ::FGengine::currentPfns.TransformFeedbackBufferRange
#define glTransformFeedbackVaryings ::FGengine::currentPfns.TransformFeedbackVaryings
#define glUniform1d ::FGengine::currentPfns.Uniform1d
#define glUniform1dv ::FGengine::currentPfns.Uniform1dv
#define glUniform1f ::FGengine::currentPfns.Uniform1f
#define glUniform1fv ::FGengine::currentPfns.Uniform1fv
#define glUniform1i ::FGengine::currentPfns.Uniform1i
#define glUniform1iv ::FGengine::currentPfns.Uniform1iv
#define glUniform1ui ::FGengine::currentPfns.Uniform1ui
#define glUniform1uiv ::FGengine::currentPfns.Uniform1uiv
#define glUniform2d ::FGengine::currentPfns.Uniform2d
#define glUniform2dv ::FGengine::currentPfns.Uniform2dv
#define glUniform2f ::FGengine::currentPfns.Uniform2f
#define glUniform2fv ::FGengine::currentPfns.Uniform2fv
#define glUniform2i ::FGengine::currentPfns.Uniform2i
#define glUniform2iv ::FGengine::currentPfns.Uniform2iv
#define glUniform2ui ::FGengine::currentPfns.Uniform2ui
#define glUniform2uiv ::FGengine::currentPfns.Uniform2uiv
#define glUniform3d ::FGengine::currentPfns.Uniform3d
#define glUniform3dv ::FGengine::currentPfns.Uniform3dv
#define glUniform3f ::FGengine::currentPfns.Uniform3f
#define glUniform3fv ::FGengine::currentPfns.Uniform3fv
#define glUniform3i ::FGengine::currentPfns.Uniform3i
#define glUniform3iv ::FGengine::currentPfns.Uniform3iv
#define glUniform3ui ::FGengine::currentPfns.Uniform3ui
#define glUniform3uiv ::FGengine::currentPfns.Uniform3uiv
#define glUniform4d ::FGengine::currentPfns.Uniform4d
#define glUniform4dv ::FGengine::currentPfns.Uniform4dv
#define glUniform4f ::FGengine::currentPfns.Uniform4f
#define glUniform4fv ::FGengine::currentPfns.Uniform4fv
#define glUniform4i ::FGengine::currentPfns.Uniform4i
#define glUniform4iv ::FGengine::currentPfns.Uniform4iv
#define glUniform4ui ::FGengine::currentPfns.Uniform4ui
#define glUniform4uiv ::FGengine::currentPfns.Uniform4uiv
#define glUniformBlockBinding ::FGengine::currentPfns.UniformBlockBinding
#define glUniformMatrix2dv ::FGengine::currentPfns.UniformMatrix2dv
#define glUniformMatrix2fv ::FGengine::currentPfns.UniformMatrix2fv
#define glUniformMatrix2x3dv ::FGengine::currentPfns.UniformMatrix2x3dv
#define glUniformMatrix2x3fv ::FGengine::currentPfns.UniformMatrix2x3fv
#define glUniformMatrix2x4dv ::FGengine::currentPfns.UniformMatrix2x4dv
#define glUniformMatrix2x4fv ::FGengine::currentPfns.UniformMatrix2x4fv
#define glUniformMatrix3dv ::FGengine::currentPfns.UniformMatrix3dv
#define glUniformMatrix3fv ::FGengine::currentPfns.UniformMatrix3fv
#define glUniformMatrix3x2dv ::FGengine::currentPfns.UniformMatrix3x2dv
#define glUniformMatrix3x2fv ::FGengine::currentPfns.UniformMatrix3x2fv
#define glUniformMatrix3x4dv ::FGengine::currentPfns.UniformMatrix3x4dv
#define glUniformMatrix3x4fv ::FGengine::currentPfns.UniformMatrix3x4fv
#define glUniformMatrix4dv ::FGengine::currentPfns.UniformMatrix4dv
#define glUniformMatrix4fv ::FGengine::currentPfns.UniformMatrix4fv
#define glUniformMatrix4x2dv ::FGengine::currentPfns.UniformMatrix4x2dv
#define glUniformMatrix4x2fv ::FGengine::currentPfns.UniformMatrix4x2fv
#define glUniformMatrix4x3dv ::FGengine::currentPfns.UniformMatrix4x3dv
#define glUniformMatrix4x3fv ::FGengine::currentPfns.UniformMatrix4x3fv
#define glUniformSubroutinesuiv ::FGengine::currentPfns.UniformSubroutinesuiv
#define glUnmapBuffer ::FGengine::currentPfns.UnmapBuffer
#define glUnmapNamedBuffer ::FGengine::currentPfns.UnmapNamedBuffer
#define glUseProgram ::FGengine::currentPfns.UseProgram
#define glUseProgramStages ::FGengine::currentPfns.UseProgramStages
#define glValidateProgram ::FGengine::currentPfns.ValidateProgram
#define glValidateProgramPipeline ::FGengine::currentPfns.ValidateProgramPipeline
#define glVertexArrayAttribBinding ::FGengine::currentPfns.VertexArrayAttribBinding
#define glVertexArrayAttribFormat ::FGengine::currentPfns.VertexArrayAttribFormat
#define glVertexArrayAttribIFormat ::FGengine::currentPfns.VertexArrayAttribIFormat
#define glVertexArrayAttribLFormat ::FGengine::currentPfns.VertexArrayAttribLFormat
#define glVertexArrayBindingDivisor ::FGengine::currentPfns.VertexArrayBindingDivisor
#define glVertexArrayElementBuffer ::FGengine::currentPfns.VertexArrayElementBuffer
#define glVertexArrayVertexBuffer ::FGengine::currentPfns.VertexArrayVertexBuffer
#define glVertexArrayVertexBuffers ::FGengine::currentPfns.VertexArrayVertexBuffers
#define glVertexAttrib1d ::FGengine::currentPfns.VertexAttrib1d
#define glVertexAttrib1dv ::FGengine::currentPfns.VertexAttrib1dv
#define glVertexAttrib1f ::FGengine::currentPfns.VertexAttrib1f
#define glVertexAttrib1fv ::FGengine::currentPfns.VertexAttrib1fv
#define glVertexAttrib1s ::FGengine::currentPfns.VertexAttrib1s
#define glVertexAttrib1sv ::FGengine::currentPfns.VertexAttrib1sv
#define glVertexAttrib2d ::FGengine::currentPfns.VertexAttrib2d
#define glVertexAttrib2dv ::FGengine::currentPfns.VertexAttrib2dv
#define glVertexAttrib2f ::FGengine::currentPfns.VertexAttrib2f
#define glVertexAttrib2fv ::FGengine::currentPfns.VertexAttrib2fv
#define glVertexAttrib2s ::FGengine::currentPfns.VertexAttrib2s
#define glVertexAttrib2sv ::FGengine::currentPfns.VertexAttrib2sv
#define glVertexAttrib3d ::FGengine::currentPfns.VertexAttrib3d
#define glVertexAttrib3dv ::FGengine::currentPfns.VertexAttrib3dv
#define glVertexAttrib3f ::FGengine::currentPfns.VertexAttrib3f
#define glVertexAttrib3fv ::FGengine::currentPfns.VertexAttrib3fv
#define glVertexAttrib3s ::FGengine::currentPfns.VertexAttrib3s
#define glVertexAttrib3sv ::FGengine::currentPfns.VertexAttrib3sv
#define glVertexAttrib4Nbv ::FGengine::currentPfns.VertexAttrib4Nbv
#define glVertexAttrib4Niv ::FGengine::currentPfns.VertexAttrib4Niv
#define glVertexAttrib4Nsv ::FGengine::currentPfns.VertexAttrib4Nsv
#define glVertexAttrib4Nub ::FGengine::currentPfns.VertexAttrib4Nub
#define glVertexAttrib4Nubv ::FGengine::currentPfns.VertexAttrib4Nubv
#define glVertexAttrib4Nuiv ::FGengine::currentPfns.VertexAttrib4Nuiv
#define glVertexAttrib4Nusv ::FGengine::currentPfns.VertexAttrib4Nusv
#define glVertexAttrib4bv ::FGengine::currentPfns.VertexAttrib4bv
#define glVertexAttrib4d ::FGengine::currentPfns.VertexAttrib4d
#define glVertexAttrib4dv ::FGengine::currentPfns.VertexAttrib4dv
#define glVertexAttrib4f ::FGengine::currentPfns.VertexAttrib4f
#define glVertexAttrib4fv ::FGengine::currentPfns.VertexAttrib4fv
#define glVertexAttrib4iv ::FGengine::currentPfns.VertexAttrib4iv
#define glVertexAttrib4s ::FGengine::currentPfns.VertexAttrib4s
#define glVertexAttrib4sv ::FGengine::currentPfns.VertexAttrib4sv
#define glVertexAttrib4ubv ::FGengine::currentPfns.VertexAttrib4ubv
#define glVertexAttrib4uiv ::FGengine::currentPfns.VertexAttrib4uiv
#define glVertexAttrib4usv ::FGengine::currentPfns.VertexAttrib4usv
#define glVertexAttribBinding ::FGengine::currentPfns.VertexAttribBinding
#define glVertexAttribDivisor ::FGengine::currentPfns.VertexAttribDivisor
#define glVertexAttribFormat ::FGengine::currentPfns.VertexAttribFormat
#define glVertexAttribI1i ::FGengine::currentPfns.VertexAttribI1i
#define glVertexAttribI1iv ::FGengine::currentPfns.VertexAttribI1iv
#define glVertexAttribI1ui ::FGengine::currentPfns.VertexAttribI1ui
#define glVertexAttribI1uiv ::FGengine::currentPfns.VertexAttribI1uiv
#define glVertexAttribI2i ::FGengine::currentPfns.VertexAttribI2i
#define glVertexAttribI2iv ::FGengine::currentPfns.VertexAttribI2iv
#define glVertexAttribI2ui ::FGengine::currentPfns.VertexAttribI2ui
#define glVertexAttribI2uiv ::FGengine::currentPfns.VertexAttribI2uiv
#define glVertexAttribI3i ::FGengine::currentPfns.VertexAttribI3i
#define glVertexAttribI3iv ::FGengine::currentPfns.VertexAttribI3iv
#define glVertexAttribI3ui ::FGengine::currentPfns.VertexAttribI3ui
#define glVertexAttribI3uiv ::FGengine::currentPfns.VertexAttribI3uiv
#define glVertexAttribI4bv ::FGengine::currentPfns.VertexAttribI4bv
#define glVertexAttribI4i ::FGengine::currentPfns.VertexAttribI4i
#define glVertexAttribI4iv ::FGengine::currentPfns.VertexAttribI4iv
#define glVertexAttribI4sv ::FGengine::currentPfns.VertexAttribI4sv
#define glVertexAttribI4ubv ::FGengine::currentPfns.VertexAttribI4ubv
#define glVertexAttribI4ui ::FGengine::currentPfns.VertexAttribI4ui
#define glVertexAttribI4uiv ::FGengine::currentPfns.VertexAttribI4uiv
#define glVertexAttribI4usv ::FGengine::currentPfns.VertexAttribI4usv
#define glVertexAttribIFormat ::FGengine::currentPfns.VertexAttribIFormat
#define glVertexAttribIPointer ::FGengine::currentPfns.VertexAttribIPointer
#define glVertexAttribL1d ::FGengine::currentPfns.VertexAttribL1d
#define glVertexAttribL1dv ::FGengine::currentPfns.VertexAttribL1dv
#define glVertexAttribL2d ::FGengine::currentPfns.VertexAttribL2d
#define glVertexAttribL2dv ::FGengine::currentPfns.VertexAttribL2dv
#define glVertexAttribL3d ::FGengine::currentPfns.VertexAttribL3d
#define glVertexAttribL3dv ::FGengine::currentPfns.VertexAttribL3dv
#define glVertexAttribL4d ::FGengine::currentPfns.VertexAttribL4d
#define glVertexAttribL4dv ::FGengine::currentPfns.VertexAttribL4dv
#define glVertexAttribLFormat ::FGengine::currentPfns.VertexAttribLFormat
#define glVertexAttribLPointer ::FGengine::currentPfns.VertexAttribLPointer
#define glVertexAttribP1ui ::FGengine::currentPfns.VertexAttribP1ui
#define glVertexAttribP1uiv ::FGengine::currentPfns.VertexAttribP1uiv
#define glVertexAttribP2ui ::FGengine::currentPfns.VertexAttribP2ui
#define glVertexAttribP2uiv ::FGengine::currentPfns.VertexAttribP2uiv
#define glVertexAttribP3ui ::FGengine::currentPfns.VertexAttribP3ui
#define glVertexAttribP3uiv ::FGengine::currentPfns.VertexAttribP3uiv
#define glVertexAttribP4ui ::FGengine::currentPfns.VertexAttribP4ui
#define glVertexAttribP4uiv ::FGengine::currentPfns.VertexAttribP4uiv
#define glVertexAttribPointer ::FGengine::currentPfns.VertexAttribPointer
#define glVertexBindingDivisor ::FGengine::currentPfns.VertexBindingDivisor
#define glViewport ::FGengine::currentPfns.Viewport
#define glViewportArrayv ::FGengine::currentPfns.ViewportArrayv
#define glViewportIndexedf ::FGengine::currentPfns.ViewportIndexedf
#define glViewportIndexedfv ::FGengine::currentPfns.ViewportIndexedfv
#define glWaitSync ::FGengine::currentPfns.WaitSync
